import type { Category, Exercise, MuscleGroup } from '../../types';
import type { Anim, Held, Highlight, Part } from './engine';
import { PATTERNS, type PatternId } from './patterns';

/** Движение для каждого упражнения библиотеки; второй элемент — другой снаряд в руках. */
const BY_ID: Record<string, PatternId | [PatternId, Held[]]> = {
  'jumping-jacks': 'jumpingJacks',
  'high-knees': 'highKnees',
  'butt-kicks': 'buttKicks',
  'leg-swings': 'legSwings',
  'worlds-greatest-stretch': 'worldsGreatest',
  'arm-circles': 'armCircles',
  'a-skip': 'aSkip',
  'neck-warmup': 'neckMobility',
  inchworm: 'inchworm',
  'cat-cow': 'catCow',
  'thoracic-rotation': 'thoracicRotation',
  'hip-flexor-stretch': 'hipFlexorStretch',
  'hamstring-stretch': 'hamstringStretch',
  'quad-stretch': 'quadStretch',
  'childs-pose': 'childsPose',
  'foam-rolling': 'foamRoll',
  'box-breathing': 'breathing',
  squat: 'squat',
  'goblet-squat': 'gobletSquat',
  'back-squat': 'backSquat',
  'bulgarian-split-squat': 'bulgarian',
  lunges: 'lunge',
  'lateral-lunge': 'lateralLunge',
  'romanian-deadlift': 'rdl',
  'single-leg-rdl': 'singleLegRdl',
  'glute-bridge': 'gluteBridge',
  'nordic-curl': 'nordicCurl',
  'copenhagen-plank': 'copenhagen',
  'calf-raise': 'calfRaise',
  'step-up': 'stepUp',
  'wall-sit': 'wallSit',
  'kettlebell-swing': 'kbSwing',
  'push-up': 'pushUp',
  'pike-push-up': 'pikePushUp',
  'pull-up': 'pullUp',
  'inverted-row': 'invertedRow',
  'dumbbell-row': 'dbRow',
  'overhead-press': 'dbOhPress',
  dips: 'benchDips',
  'band-pull-apart': 'bandPullApart',
  'face-pull': 'facePull',
  'external-rotation': 'externalRotation',
  'ytw-raises': 'ytw',
  'band-lat-pulldown': 'bandPulldown',
  'neck-isometric': 'neckIso',
  'neck-band': 'neckMobility',
  'lateral-neck-hold': 'lateralNeck',
  'plate-steering': 'plateSteering',
  'farmers-walk': 'farmersWalk',
  'wrist-curl': 'wristCurl',
  'plate-pinch': 'platePinch',
  'dead-hang': 'deadHang',
  plank: 'plank',
  'side-plank': 'sidePlank',
  'hollow-hold': 'hollowHold',
  'dead-bug': 'deadBug',
  'pallof-press': 'pallofPress',
  'bird-dog': 'birdDog',
  'russian-twist': 'russianTwist',
  'mountain-climbers': 'mountainClimber',
  superman: 'superman',
  'box-jump': 'boxJump',
  'broad-jump': 'broadJump',
  'squat-jump': 'squatJump',
  'skater-jump': 'skater',
  'tuck-jump': 'tuckJump',
  'medball-slam': 'medballSlam',
  'medball-rotational-throw': 'medballRotation',
  'sprint-20': 'sprint',
  'flying-sprint': 'sprint',
  'shuttle-5-10-5': 'sprint',
  't-drill': 'lateralShuffle',
  'quick-feet': 'quickFeet',
  'lateral-shuffle': 'lateralShuffle',
  'cone-dribble': 'footDribble',
  'wall-passes': 'footDribble',
  'shadow-boxing': 'punches',
  'ball-drop-reaction': 'ballCatch',
  'reaction-test': 'phoneReaction',
  'reaction-start': 'reactionStart',
  burpee: 'burpee',
  'jump-rope': 'jumpRope',
  'easy-run': 'easyRun',
  'tempo-run': 'run',
  'interval-run': 'run',
  'bike-intervals': 'bikeSprint',
  'bike-endurance': 'bike',
  'bench-press': 'benchPress',
  'db-bench-press': 'dbBenchPress',
  'incline-db-press': ['inclinePress', ['dumbbells']],
  'db-fly': 'dbFly',
  'push-up-close': 'closePushUp',
  'barbell-row': 'barbellRow',
  deadlift: 'deadlift',
  'barbell-ohp': 'ohPress',
  'lat-pulldown': 'latPulldown',
  'cable-row': 'cableRow',
  'leg-press': 'legPress',
  'leg-curl': 'legCurl',
  'leg-extension': 'legExtension',
  'hip-thrust': 'hipThrust',
  'lateral-raise': 'lateralRaise',
  'biceps-curl': 'curl',
  'hammer-curl': 'curl',
  'triceps-extension': 'tricepsExtension',
  'db-thruster': 'thruster',
  'incline-walk': 'walk',
  crunches: 'crunch',
  'leg-raises': 'legRaise',
  'incline-bench-press': 'inclinePress',
  'close-grip-bench': 'benchPress',
  'cable-crossover': 'cableCrossover',
  't-bar-row': 'tBarRow',
  'barbell-shrug': 'shrug',
  hyperextension: 'hyperextension',
  'front-squat': 'frontSquat',
  'hack-squat': 'hackSquat',
  'machine-calf-raise': 'machineCalfRaise',
  'db-shoulder-press': 'seatedDbPress',
  'upright-row': 'uprightRow',
  'rear-delt-fly': 'rearDeltFly',
  'front-raise': 'frontRaise',
  'barbell-curl': 'barbellCurl',
  'preacher-curl': 'preacherCurl',
  'skull-crusher': 'skullCrusher',
  'triceps-pushdown': 'tricepsPushdown',
  'power-clean': 'powerClean',
  'push-press': 'pushPress',
  'hip-circles': 'hipCircles',
  carioca: 'carioca',
  'ankle-mobility': 'ankleMobility',
  'shoulder-dislocates': 'shoulderDislocates',
  'pigeon-stretch': 'pigeon',
  'chest-doorway-stretch': 'chestStretch',
  'calf-stretch': 'calfStretch',
  'neck-stretch': 'neckStretch',
  'ball-juggling': 'juggling',
  'first-touch-turn': 'footDribble',
  'repeated-sprints': 'sprint',
  'yo-yo-shuttle': 'run',
  'lateral-band-walk': 'bandWalk',
  'single-leg-hop-stick': 'singleLegHop',
  'wrist-roller': 'wristRoller',
  'reverse-wrist-curl': 'wristCurl',
  'gripper-squeeze': 'gripper',
  'band-steering-hold': 'bandSteering',
  'peripheral-reaction': 'readyStance',
  'single-leg-press': 'singleLegPress',
  strides: 'run',
  'hill-sprints': 'sprint',
  'long-run': 'easyRun',
  fartlek: 'run',
  'single-leg-calf-raise': 'singleCalfRaise',
  'tibialis-raise': 'tibialisRaise',
  'cossack-squat': 'cossack',
  'landmine-rotation': 'landmineRotation',
  stickhandling: 'stickhandling',
  'crossover-start': 'reactionStart',
  'groin-squeeze': 'groinSqueeze',
  'depth-jump': 'depthJump',
  'closeout-drill': 'lateralShuffle',
  'ball-handling': 'basketDribble',
  'pogo-jumps': 'pogo',
  'lateral-hops-line': 'lateralHops',
  'split-step-reaction': 'splitStep',
  'medball-overhead-throw': 'medballOverhead',
  'band-internal-rotation': 'internalRotation',
  'spider-drill': 'lateralShuffle',
  'woodchop-band': 'woodchop',
  sprawl: 'sprawl',
  'plank-shoulder-taps': 'shoulderTaps',
  'band-punches': 'punches',
  'kettlebell-halo': 'kbHalo',
  'bear-crawl': 'bearCrawl',
  'streamline-hold': 'streamline',
  'band-straight-arm-pulldown': 'straightArmPulldown',
  'flutter-kicks': 'flutterKicks',
  'prone-swimmers': 'proneSwimmer',
  'y-raise-incline': 'yRaise',
  'thoracic-extension-roller': 'thoracicRoller',
  'step-down': 'stepDown',
  'bike-threshold': 'bike',
  'bike-sprints': 'bikeSprint',
  clamshell: 'clamshell',
  'hip-flexor-march': 'hipMarch',
  'reverse-lunge': 'reverseLunge',
  'sumo-squat': 'sumoSquat',
  'glute-kickback': 'gluteKickback',
  'bicycle-crunch': 'bicycleCrunch',
  'rower-intervals': 'rower',
  'sumo-deadlift': 'sumoDeadlift',
  'pause-squat': 'pauseSquat',
  'good-morning': 'goodMorning',
  'chin-up': 'chinUp',
  'hang-power-snatch': 'hangSnatch',
  'dumbbell-pullover': 'pullover',
  'turkish-get-up': 'turkishGetUp',
  'jumping-lunges': 'jumpingLunge',
  'wall-ball': 'wallBall',
  'hanging-knee-raise': 'hangingKneeRaise',
};

/** Для упражнений из wger, от ИИ и своих — поиск по названию (рус./англ.). */
const BY_NAME: [RegExp, PatternId][] = [
  [/бёрпи|берпи|burpee/, 'burpee'],
  [/скакалк|jump ?rope|skipping/, 'jumpRope'],
  [/велосипед|велотренаж|bike|cycl/, 'bike'],
  [/гребн|rowing machine|rower|ergo/, 'rower'],
  [/подтяг|pull-?up|chin-?up/, 'pullUp'],
  [/вертикальн.*блок|верхн.*блок|pulldown|pull-down/, 'latPulldown'],
  [/горизонтальн.*блок|cable row|seated row/, 'cableRow'],
  [/становая|deadlift/, 'deadlift'],
  [/румынск|romanian|rdl|stiff/, 'rdl'],
  [/гуд ?морнинг|good ?morning/, 'goodMorning'],
  [/гиперэкст|hyperext|back extension/, 'hyperextension'],
  [/махи гир|kettlebell swing|swing/, 'kbSwing'],
  [/фронтальн.*присед|front squat/, 'frontSquat'],
  [/присед.*штанг|штанг.*присед|back squat|barbell squat/, 'backSquat'],
  [/гоблет|goblet|присед.*гантел/, 'gobletSquat'],
  [/выпрыгив|jump squat|squat jump/, 'squatJump'],
  [/присед|squat/, 'squat'],
  [/болгарск|bulgarian|split squat/, 'bulgarian'],
  [/выпад|lunge/, 'lunge'],
  [/зашагив|step-?up/, 'stepUp'],
  [/жим ногами|leg press/, 'legPress'],
  [/разгибан.*ног|leg extension/, 'legExtension'],
  [/сгибан.*ног|leg curl|hamstring curl/, 'legCurl'],
  [/ягодичн.*мост|мостик|glute bridge|hip thrust|bridge/, 'gluteBridge'],
  [/носк|икр|calf/, 'calfRaise'],
  [/отжиман.*брус|dips?\b/, 'benchDips'],
  [/отжим|push-?up|press-?up/, 'pushUp'],
  [/жим.*наклон|incline/, 'inclinePress'],
  [/жим.*гантел.*леж|dumbbell bench/, 'dbBenchPress'],
  [/разведен.*леж|fly|flye|бабочк|pec deck/, 'dbFly'],
  [/кроссовер|crossover/, 'cableCrossover'],
  [/жим.*леж|bench press|chest press/, 'benchPress'],
  [/пуловер|pullover/, 'pullover'],
  [/француз|skull ?crusher|lying triceps/, 'skullCrusher'],
  [/разгибан.*блок|pushdown|push-down/, 'tricepsPushdown'],
  [/трицепс|triceps|разгибан.*рук/, 'tricepsExtension'],
  [/скотт|preacher/, 'preacherCurl'],
  [/штанг.*бицепс|barbell curl/, 'barbellCurl'],
  [/бицепс|сгибан.*рук|curl/, 'curl'],
  [/запяст|wrist/, 'wristCurl'],
  [/шраг|shrug/, 'shrug'],
  [/к подбородку|upright row/, 'uprightRow'],
  [/в стороны|lateral raise|side raise/, 'lateralRaise'],
  [/перед собой|front raise/, 'frontRaise'],
  [/в наклоне.*развед|rear delt|reverse fly/, 'rearDeltFly'],
  [/тяга.*гантел|dumbbell row|one arm row/, 'dbRow'],
  [/тяга|row/, 'barbellRow'],
  [/швунг|push press/, 'pushPress'],
  [/жим.*сидя|seated.*press/, 'seatedDbPress'],
  [/жим.*гантел|dumbbell.*press|arnold/, 'dbOhPress'],
  [/жим|press/, 'ohPress'],
  [/взятие|clean/, 'powerClean'],
  [/рывок|snatch/, 'hangSnatch'],
  [/трастер|thruster/, 'thruster'],
  [/вис\b|hang/, 'deadHang'],
  [/боков.*планк|side plank/, 'sidePlank'],
  [/планк|plank/, 'plank'],
  [/скалолаз|mountain climb/, 'mountainClimber'],
  [/велосипед|bicycle crunch/, 'bicycleCrunch'],
  [/русск|russian twist|twist/, 'russianTwist'],
  [/подъём ног|подъем ног|leg raise/, 'legRaise'],
  [/лодочк|hollow/, 'hollowHold'],
  [/скручив|crunch|пресс|sit-?up|abs/, 'crunch'],
  [/супермен|superman/, 'superman'],
  [/птица|bird ?dog/, 'birdDog'],
  [/прыжк.*тумб|box jump/, 'boxJump'],
  [/в длину|broad jump/, 'broadJump'],
  [/прыж|jump|hop/, 'squatJump'],
  [/спринт|ускорен|sprint/, 'sprint'],
  [/бег|run|jog/, 'run'],
  [/ходьб|walk/, 'walk'],
  [/бой с тенью|shadow|удар|punch|box/, 'punches'],
  [/мяч.*стен|wall ball/, 'wallBall'],
  [/медбол|slam/, 'medballSlam'],
  [/растяж|stretch/, 'hamstringStretch'],
  [/шея|шеи|neck/, 'neckMobility'],
];

const BY_MUSCLE: Record<MuscleGroup, PatternId> = {
  chest: 'pushUp',
  back: 'barbellRow',
  shoulders: 'dbOhPress',
  arms: 'curl',
  forearms: 'wristCurl',
  core: 'plank',
  glutes: 'gluteBridge',
  quads: 'squat',
  hamstrings: 'rdl',
  adductors: 'lateralLunge',
  calves: 'calfRaise',
  neck: 'neckMobility',
};

const BY_CATEGORY: Partial<Record<Category, PatternId>> = {
  warmup: 'jumpingJacks',
  mobility: 'catCow',
  cooldown: 'hamstringStretch',
  power: 'squatJump',
  speed: 'sprint',
  agility: 'lateralShuffle',
  endurance: 'run',
  reaction: 'readyStance',
  skill: 'readyStance',
};

const PART_OF: Record<MuscleGroup, Part> = {
  neck: 'neck',
  shoulders: 'shoulders',
  chest: 'torso',
  back: 'torso',
  core: 'torso',
  arms: 'upperArm',
  forearms: 'forearm',
  glutes: 'glutes',
  quads: 'thigh',
  hamstrings: 'thigh',
  adductors: 'thigh',
  calves: 'shin',
};

export type AnimatedExercise = Pick<Exercise, 'category' | 'muscles'> & { exerciseId?: string; id?: string; name: string };

/** Подсветка мышц: первая мышца в списке — основная. */
export function highlightFor(muscles: MuscleGroup[]): Highlight {
  const hl: Highlight = {};
  muscles.forEach((m, i) => {
    const part = PART_OF[m];
    const level = i === 0 ? 2 : 1;
    if ((hl[part] ?? 0) < level) hl[part] = level;
  });
  return hl;
}

export function patternIdFor(ex: AnimatedExercise): PatternId {
  const id = ex.exerciseId ?? ex.id ?? '';
  const direct = BY_ID[id];
  if (direct) return Array.isArray(direct) ? direct[0] : direct;
  const name = ex.name.toLowerCase();
  for (const [re, p] of BY_NAME) if (re.test(name)) return p;
  if (ex.category === 'strength' || ex.category === 'core') return ex.muscles[0] ? BY_MUSCLE[ex.muscles[0]] : 'squat';
  return BY_CATEGORY[ex.category] ?? (ex.muscles[0] ? BY_MUSCLE[ex.muscles[0]] : 'stand');
}

/** Анимация и подсветка для упражнения (встроенного, из wger, от ИИ или своего). */
export function animationFor(ex: AnimatedExercise): { id: PatternId; anim: Anim; highlight: Highlight } {
  const pid = patternIdFor(ex);
  const direct = BY_ID[ex.exerciseId ?? ex.id ?? ''];
  const base: Anim = PATTERNS[pid];
  const anim = Array.isArray(direct) ? { ...base, held: direct[1] } : base;
  return { id: pid, anim, highlight: highlightFor(ex.muscles) };
}

export const MAPPED_IDS = Object.keys(BY_ID);
